### PR TITLE
Added Profile Page and Booking Cancel Validation

### PR DESCRIPTION
**Pull request by RonnieArvanites**
**Summary**
-Added Profile Page
-Added the ability to cancel bookings on the frontend
-Added logic to the cancel booking backend route to check that the user requesting to cancel the booking is either the listing owner or the person who created the booking
-Added a date check to make sure the time is at least 2 days before the start date of the booking.

### CODE REVIEW

**Review by davidtayloryangg — CHANGES_REQUESTED** [review]
Needs to update with main

**Comment by RonnieArvanites** [comment]
> Needs to update with main

PR updated with main

**Review by LDomadia — CHANGES_REQUESTED** [review]
Two things:
- Under upcoming bookings, it says "undefined"
- this is super minor and cosmetic, are you able to take the user's display name and show it next to the icon? I think that would make it look really nice!
Screen Shot 2022-12-16 at 6 25 32 PM

**Review by LDomadia — APPROVED** [review]

**Review by davidtayloryangg — APPROVED** [review]

**Comment by LDomadia** [comment]
Looks good!

**Pull request merged**
