### PR TITLE
Search page

### PR DESCRIPTION
**Pull request by davidtayloryangg**
image

Search: Google Places Auto Complete when typing in the search bar.
Button makes the axios call to backend with use effect and hooks. 

image

Comment out line 94-97 to see what it returns.

Pagination changed to normal The Load More way was not that good looking. 

9 Listings on each page and then map with markers for each listing shown. No URL pagination

### CODE REVIEW

**Review by uityh — CHANGES_REQUESTED** [review]
Looks good!. Just some tota11y issues that need to be fixed.
image
image
image

**Comment by davidtayloryangg** [comment]
@uityh 
Done! -> Note to self totally wants A tags to be longer LOL

**Review by uityh — APPROVED** [review]
Looks good!

**Comment by LDomadia** [comment]
Looks good!

**Review by LDomadia — APPROVED** [review]

**Pull request merged**
